window:
  startup_mode: SimpleFullscreen

alt_send_esc: false
live_config_reload: true

key_bindings:
  # Cmd + Välilyönti: kiinteä NUL
  - { key: Space, mods: Control, chars: "\x00" }
  # Cmd + Vasen/Oikea: vaihda Tmux-istuntoa
  - { key: Left, mods: Command, chars: "\x00\x28" }
  - { key: Right, mods: Command, chars: "\x00\x29" }
